### ISSUE TITLE
Missing dependencies..

### ISSUE THREAD

**Issue by Chaos192** [namreeb/hacksniff#1]
Can you include the missing libs and such? or contact me via email at rynerlutetld@hotmail.com as I really want to use this tool...

**Comment by namreeb** [comment]
The only dependency is hadesmem.  It can be found here: https://github.com/RaptorFactor/hadesmem

**Comment by Chaos192** [comment]
#include <boost/program_options.hpp>
#include <boost/exception/diagnostic_information.hpp>

which then requires asmjit and a couple others... Thanks a lot for quick response. I am wondering if this can be used to sniff what manual mapped .dlls do to other processes as well as that would be a neat feature.

**Comment by namreeb** [comment]
Oh sorry you're right. It's been a while since I've looked at this code. It does require boost, too. Also, hadesmem itself has some dependencies. Asmjit is among them.

**Comment by Chaos192** [comment]
Yeah no worries right now having issues getting one of their dependencies to compile the lib I need which is why I brought this up.
